name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby
          gem install mustache

      - name: Run build script
        run: bash ./build.sh

      - name: Push to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: "output"
          destination-github-username: youdame
          destination-repository-name: react-vote-19th
          user-email: ${{ secrets.EMAIL }}
          commit-message: "Deploy from GitHub Actions"
          target-branch: main

      - name: Verify push to another repository
        run: echo "Pushed to the destination repository"
